### ISSUE TITLE
pip failure

### ISSUE THREAD

**Issue by rhysaph** [ska-sa/katdal#141]
Hi,

When I try to install katdal with pip I get the following.
Am I doing anything wrong?

Thanks,
Rhys Morris

 pip3.6 install katdal --user
Collecting katdal
  Downloading https://files.pythonhosted.org/packages/cd/1f/1aa5d487dc3e28d180cabdc2fd0ce158455e557bdbe1a2ec1cf57c23434a/katdal-0.9.5.tar.gz (129kB)
█████████████████| 133kB 359kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-l7y6hjr3/katdal/setup.py", line 26, in <module>
        news = open(os.path.join(here, 'NEWS.rst')).read()
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-l7y6hjr3/katdal/NEWS.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-l7y6hjr3/katdal/
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by ludwigschwardt** [comment]
This is somewhat embarrrassing... katdal currently only works on Python 2. I’m upping the priority on Python 3 support!

**Comment by bmerry** [comment]
katdal now supports Python 3, so this should work now.
