### ISSUE TITLE
Missing dependencies on master

### ISSUE THREAD

**Issue by bennahugo** [ska-sa/katdal#143]
Following the authenticated guide. The following dependencies are missing:
```
rdbtools
botocore
```

**Comment by ludwigschwardt** [comment]
See PR #139 :-) You might also want to install `python-lzf`.

**Comment by ludwigschwardt** [comment]
Actually, PR #139 still needs to get updated requirements - let's leave that for the next PR. Also, you probably want to install katdal as:

```pip install katdal[ms,s3]```

since S3 and MS support is effectively optional.

**Comment by bennahugo** [comment]
thanks @ludwigschwardt

**Comment by bmerry** [comment]
@bennahugo is this resolved now?

**Comment by ludwigschwardt** [comment]
@bennahugo, another ping now that we are on katdal 0.12...

**Comment by bennahugo** [comment]
Sorry missed this one when I was on sick leave. It looks like it has been fixed a long time ago, thanks. Closing
