### ISSUE TITLE
Need a nice file identifier from katdal object

### ISSUE THREAD

**Issue by spassmoor** [ska-sa/katdal#283]
katdal needs to provided a unique identifier that can be used to produce file for data products that don't clobber each other.

I have used :
filename.split('/')[-1].split('?')[0] 
where file name could be a file or a url with token. 
But it is getting cumbersome .

**Comment by cchristelis** [comment]
@spassmoor , I think the change made in https://github.com/ska-sa/katdal/pull/337 addresses this enhancement request.

**Comment by spassmoor** [comment]
Yes  thanks

**Comment by ludwigschwardt** [comment]
There are probably a few `nice_filename` instances in `katsdpscripts` that can be updated :-)
