### ISSUE TITLE
Pickle valued telescope state

### ISSUE THREAD

**Issue by MziyandaAstro** [ska-sa/katdal#313]

**Comment by MziyandaAstro** [comment]
Hi Guys.

I'm working on I'm trying to use katdal but the first run gives off an error 
"The telescope state contains pickled values. This is a security risk, so is disabled by default. If you trust the source of the data, you can allow the pickles to be loaded by setting KATSDPTELSTATE_ALLOW_PICKLE=1 in the environment. This is needed for MeerKAT data up to March 2019."
I'm not too sure what this means . Can someone please help me out on this.

Cheers
Mziyanda

**Comment by ludwigschwardt** [comment]
Hi Mziyanda,

If you want to open older data files with a recent katdal, run the following shell command on the command line before running your script / ipython:
```Bash
export KATSDPTELSTATE_ALLOW_PICKLE=1
```
You can also add the line to your `~/.bashrc` or `~/.bash_profile` config file if you want to enable it all the time.

**Comment by MziyandaAstro** [comment]
Thanks alot Ludwig.

CheersMzi
    On Tuesday, 29 September 2020, 18:31:41 SAST, Ludwig Schwardt <notifications@github.com> wrote:  
 
 


Hi Mziyanda,

If you want to open older data files with a recent katdal, run the following shell command on the command line before running your script / ipython:
export KATSDPTELSTATE_ALLOW_PICKLE=1
You can also add the line to your ~/.bashrc or ~/.bash_profile config file if you want to enable it all the time.
