### ISSUE TITLE
Problem when downloading raw data from SARAO using mvf_download.py

### ISSUE THREAD

**Issue by mariogrs** [ska-sa/katdal#378]
This only happens  with certain files. Seems an issue with _blocks_ravel:

Traceback (most recent call last):
  File "/idia/projects/hi_im/transfer_scripts/katdal/bin/mvf_download.py", line 246, in <module>
    if not main():
  File "/idia/projects/hi_im/transfer_scripts/katdal/bin/mvf_download.py", line 232, in main
    chunks.update(stream_graphs(view, store, d.vis.keep))
  File "/idia/projects/hi_im/transfer_scripts/katdal/bin/mvf_download.py", line 142, in stream_graphs
    kept_blocks = _blocks_ravel(dask_getitem(darray, keep[:darray.ndim]))
  File "/idia/projects/hi_im/transfer_scripts/katdal/lib/python3.8/site-packages/katdal/lazy_indexer.py", line 129, in dask_getitem
    indices = _simplify_index(indices, x.shape)
  File "/idia/projects/hi_im/transfer_scripts/katdal/lib/python3.8/site-packages/katdal/lazy_indexer.py", line 76, in _simplify_index
    indices = da.slicing.normalize_index(indices, shape)
  File "/idia/projects/hi_im/transfer_scripts/katdal/lib/python3.8/site-packages/dask/array/slicing.py", line 917, in normalize_index
    check_index(axis, i, d)
  File "/idia/projects/hi_im/transfer_scripts/katdal/lib/python3.8/site-packages/dask/array/slicing.py", line 975, in check_index
    raise IndexError(
IndexError: Boolean array with size 4158 is not long enough for axis 0 with size 4157

**Comment by ludwigschwardt** [comment]
Thanks Mário! Could you provide the CBID and command line options you used, and is it repeatable?

**Comment by mariogrs** [comment]
CBID: 1711214488
It is repeatable.
I use the script below where $RDB is the token.
One question: if the transfer speed is limited by the network speed, do we
need to use DASK?
------------------------------------------------
#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=16GB
#SBATCH --job-name=sync_MVF
#SBATCH --output=logs/%x-%j.out
#SBATCH --error=logs/%x-%j.err
#SBATCH --partition=Main
#SBATCH --time=20:00:00
# #SBATCH --requeue
#SBATCH --account=b10-intensitymap-ag
# #SBATCH ***@***.***
# #SBATCH --mail-type=BEGIN,END,FAIL,TIME_LIMIT_80

source /idia/projects/hi_im/transfer_scripts/katdal/bin/activate
module load rclone
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

RDB=$1
dest=$2

which rclone
echo $RDB
echo $dest

mvf_download.py --workers=$SLURM_CPUS_PER_TASK $RDB $dest
-----------------------------------------------------------------

**Comment by mariogrs** [comment]
Is there any other way to transfer the raw data?

**Comment by ludwigschwardt** [comment]
I have a fix in the works, which should be ready for testing soon.

**Comment by ludwigschwardt** [comment]
Hi Mário, see if the latest version on the branch works for you.

**Comment by mariogrs** [comment]
Thanks Ludwig! There were some network hiccups last week but I can confirm that the transfer is working fine otherwise. I'm going to take a look at the data itself but I assume there is no reason for it to be affected.

**Comment by ludwigschwardt** [comment]
Great! This issue occurred up front, before any data was transferred. Once it actually downloads, the data should be fine. Depending on the data shapes you might lose the last dump (or get an extra dump that is "lost", more likely).

**Comment by ludwigschwardt** [comment]
Fixed in katdal 0.23.
