### ISSUE TITLE
uvw coordinates calculated from wrong coordinate centre

### ISSUE THREAD

**Issue by spassmoor** [ska-sa/katdal#88]
Looking a a data set 	1497034809.h5 where the dataset contains multiple scans where the pointing centre is kept constant but the phase centre is moved by 15 degrees. I have notice that the uvw coordinates have been calculated from the antenna pointing target and not the correlater's phase centre.

**Comment by ludwigschwardt** [comment]
Thanks for this! Please make a JIRA too... I nearly forgot about this and just randomly stumbled onto it again.

**Comment by ludwigschwardt** [comment]
The latest v4 data sets use the correct CBF target by default (i.e. the delay tracking centre).

We could backport this to the HDF5 datasets if needed (see JIRA SR-933), but closing for now.
