### ISSUE TITLE
UVW Sign Convention Issue

### ISSUE THREAD

**Issue by foxmouldy** [ska-sa/katdal#93]
We've converted DEEP2 data using `h5toms.py`, which seems to produce data which has a 180-degree rotation due to UVW sign convention issues. 

Now -- we are using KATDAL version 0.7.1. as built from KERN-2, and as released in January 2017. I see that @bmerry committed an change in April 2017 to "Fix upside-down MeerKAT images". Does this mean that our version of `h5toms.py` does/does-not make the appropriate correction?

**Comment by ludwigschwardt** [comment]
Yes,

Please update to katdal 0.8 (via pip install) or the master branch here on
github. That in turn needs the latest katpoint (0.7), just to be sure.

**Comment by foxmouldy** [comment]
Thanks Lud! You legend!
