### ISSUE TITLE
add a WEIGHT_SPECTRUM column

### ISSUE THREAD

**Issue by SpheMakh** [ska-sa/katdal#99]
Not having these weights may be limiting our dynamic range a bit. It is briefly mentioned in this PR https://github.com/ska-sa/katdal/pull/62, but seems to have fallen through the cracks.

**Comment by SpheMakh** [comment]
I now have a tool to calculate the weights using the [spec. sensitivity stats](http://public.ska.ac.za/meerkat/meerkat-schedule), but adding the column to the MS is a bit involved. So we just need it to exist in the MS, along with a SIGMA_SPECTRUM column.

**Comment by SpheMakh** [comment]
Fixed, I'll use our [msutils](https://github.com/SpheMakh/msutils/issues/5) to create and populate these columns.

**Comment by SpheMakh** [comment]
Reopening based on discussion at thermal noise breakout session 

![back](https://media.giphy.com/media/yj5UdA4elp8Wc/giphy.gif)

**Comment by ludwigschwardt** [comment]
I'm back too :smile:

This has now been implemented in #231 and should be in the next release (v0.13). Please test!

**Comment by SpheMakh** [comment]
Awesome!

**Comment by SpheMakh** [comment]
Good things come to those who weight!

**Comment by ludwigschwardt** [comment]
Can I close this?

**Comment by SpheMakh** [comment]
Yep
